import { Audiowide, Roboto } from "next/font/google";
import "./globals.css";

const audiowide = Audiowide({
  weight: "400",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${audiowide.className} ${roboto.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-[audiowide]">
        {children}
      </body>
    </html>
  );
}
